CREATE TABLE CARDIO_TRAIN (
    ID INTEGER PRIMARY KEY,
    AGE INTEGER NOT NULL,
    GENDER INTEGER NOT NULL CHECK (GENDER IN (1, 2)),
    HEIGHT INTEGER NOT NULL,
    WEIGHT REAL NOT NULL,
    AP_HI INTEGER NOT NULL,
    AP_LO INTEGER NOT NULL,
    CHOLESTEROL INTEGER NOT NULL CHECK (CHOLESTEROL IN (1, 2, 3)),
    GLUC INTEGER NOT NULL CHECK (GLUC IN (1, 2, 3)),
    SMOKE INTEGER NOT NULL CHECK (SMOKE IN (0, 1)),
    ALCO INTEGER NOT NULL CHECK (ALCO IN (0, 1)),
    ACTIVE INTEGER NOT NULL CHECK (ACTIVE IN (0, 1)),
    CARDIO INTEGER NOT NULL CHECK (CARDIO IN (0, 1))
);
