-- Q01: Total patient records
SELECT COUNT(*) AS TOTAL_ROWS FROM CARDIO_TRAIN;

-- Q02: Records with cardiovascular disease
SELECT COUNT(*) AS DISEASE_CASES FROM CARDIO_TRAIN WHERE CARDIO = 1;

-- Q03: Patient counts by gender code
SELECT GENDER, COUNT(*) AS PATIENTS FROM CARDIO_TRAIN GROUP BY GENDER ORDER BY GENDER;

-- Q04: Ten highest systolic blood pressure values
SELECT ID, AP_HI, CARDIO FROM CARDIO_TRAIN ORDER BY AP_HI DESC, ID FETCH FIRST 10 ROWS ONLY;

-- Q05: Ten heaviest patients above the average weight
SELECT ID, WEIGHT, CARDIO FROM CARDIO_TRAIN WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM CARDIO_TRAIN) ORDER BY WEIGHT DESC, ID FETCH FIRST 10 ROWS ONLY;

-- Q06: Ten patients with glucose above normal
SELECT ID, GLUC, CARDIO FROM CARDIO_TRAIN WHERE GLUC > 1 ORDER BY ID FETCH FIRST 10 ROWS ONLY;

-- Q07: Ten oldest patients (age in days)
SELECT ID, AGE, AGE / 365.0 AS AGE_YEARS, CARDIO FROM CARDIO_TRAIN ORDER BY AGE DESC, ID FETCH FIRST 10 ROWS ONLY;

-- Q08: Ten patients with cholesterol code 3
SELECT ID, CHOLESTEROL, CARDIO FROM CARDIO_TRAIN WHERE CHOLESTEROL = 3 ORDER BY ID FETCH FIRST 10 ROWS ONLY;

-- Q09: Ten patients who smoke
SELECT ID, SMOKE, CARDIO FROM CARDIO_TRAIN WHERE SMOKE = 1 ORDER BY ID FETCH FIRST 10 ROWS ONLY;

-- Q10: Ten physically active patients
SELECT ID, ACTIVE, CARDIO FROM CARDIO_TRAIN WHERE ACTIVE = 1 ORDER BY ID FETCH FIRST 10 ROWS ONLY;

-- Q11: Preview ten patient records
SELECT * FROM CARDIO_TRAIN ORDER BY ID FETCH FIRST 10 ROWS ONLY;

-- Q12: Ten lowest diastolic blood pressure values
SELECT ID, AP_LO, CARDIO FROM CARDIO_TRAIN ORDER BY AP_LO, ID FETCH FIRST 10 ROWS ONLY;

-- Q13: Ten patients who drink alcohol
SELECT ID, ALCO, CARDIO FROM CARDIO_TRAIN WHERE ALCO = 1 ORDER BY ID FETCH FIRST 10 ROWS ONLY;
